---

- name: Load OS distribution variables |Apache
  include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "../vars/default.yml"

- name: install_httpd
  package:
    name: "{{ apache_package }}"
    state: present
  notify: apache_start
  tags:
    - install-httpd

