---
- name: Load OS distribution variables |Apache
  include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "../vars/default.yml"

- name: apt_update
  apt:
    update_cache: yes
    cache_valid_time: 3600
  tags:
    - apt-update

- name: install_apache2
  package:
    name: "{{ apache_package }}"
    state: present
  notify: apache_start
  tags:
    - install-apache2
